dotenv: .env
wallets:
  account-0: ${ACCOUNT_0}
  account-1: ${ACCOUNT_1}
  account-2: ${ACCOUNT_2}

networks:
  # default: localnet
  # default: bsc-test
  default: bsc-main

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.8.2
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.2
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.2"
      - "@openzeppelin-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.2"

GITHUB_TOKEN: ${GITHUB_TOKEN}
